# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fvpn < Formula
  desc "Forest VPN CLI client for macOS, Linux, and Windows"
  homepage "https://github.com/forestvpn/cli"
  version "0.2.0-beta.31"

  depends_on "wireguard-tools"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.2.0-beta.31/fvpn_darwin_amd64.tar.gz"
      sha256 "74f17d1862b95e91d3219552db07e9caab37a7a1aa9080ff6bab893f8165510a"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/forestvpn/cli/releases/download/v0.2.0-beta.31/fvpn_darwin_arm64.tar.gz"
      sha256 "1e2608e0bf1e29a3d537270edf6e13b2db902d692535d2f9d47a7d5aa0ecf117"

      def install
        bin.install "fvpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forestvpn/cli/releases/download/v0.2.0-beta.31/fvpn_linux_arm64.tar.gz"
      sha256 "3bd484d0fc573a733f2485b30d013350b7741abb9baebc92e9ee19d1fa05e37c"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.2.0-beta.31/fvpn_linux_amd64.tar.gz"
      sha256 "7810aa11d900f46476a4bada0ff758a4f6825716b6de4108c2cbbde8d768c55f"

      def install
        bin.install "fvpn"
      end
    end
  end

  test do
    system "#{bin}/fvpn version"
  end
end
